apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: server
        image: gkulshre/adservice:v1
        ports:
        - containerPort: 9555
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
